export default {

    "en": {
      "intro.welcome.title": "Dear Family and Friends,",
      "intro.welcome.text": "We're thrilled to share the joyous news that Thuy-Duc and Moritz have eloped! In an intimate celebration of our relationship, we embarked on a unique journey, breaking away from tradition.\n\nWe studied together, we graduated together, we worked for several times together. In the meantime, we've formed our own family with the two coolest kids. Growing up together has bonded us more than any vow ever could.\nAt first, we hadn't considered getting married. However, during the challenges of the pandemic, we decided to tie the knot.\n\nWhile we missed having all of you physically present, your love and support mean the world to us.\n\nWe are looking forward to gathering with all of you to share stories, laughter, and the joy of our union.",
      "intro.welcome.out": "Thank you for being a part of our lives."
    },
    "de": {
      "intro.welcome.title": "Liebe Familie und Freunde,",
      "intro.welcome.text": "Wir freuen uns, die Nachricht zu teilen, dass Thuy-Duc und Moritz sich trauen liessen! Fern von gängigen Traditionen, begaben wir uns auf unsere einzigartige Reise und feierten zu viert.\n\nVon unserem gemeinsamen Studium bis zu unserem Abschluss und den zahlreichen beruflichen Zusammenarbeiten, haben wir unsere eigene Geschichte geformt. In der Zwischenzeit haben wir unsere eigene Familie mit den zwei coolsten Kindern gegründet. Die gemeinsamen Erfahrungen und die Erlebnisse, die wir während dem Aufwachsen geteilt haben, haben unsere Bindung und Verbundenheit stärker gemacht als sämtliche formellen Gelübde oder Versprechen. Anfangs hatten wir nie ernsthaft übers Heiraten nachgedacht.\n\nObwohl wir nicht gleichgeschlechtlich sind, finden wir es wichtig, dass alle Menschen die gleichen Rechte und Möglichkeiten haben. Die Annahme der \"Ehe für alle\" im September 2021 war ein entscheidender Schritt für die Gleichberechtigung und hat unsere Entscheidung, zu heiraten, bestärkt. Gleichzeitig hat uns auch die Erfahrung der Pandemie dazu bewegt, diesen Schritt zu gehen und uns das Jawort zu geben.\n\nWir möchten unsere beiden Freunde Benjamin und Michael würdigen, die als unsere Trauzeugen eine besondere Rolle spielen. Eure Unterstützung und Freundschaft bedeuten uns unendlich viel, und wir sind dankbar, euch an unserer Seite zu haben.\n\nBesonders erinnern wir uns an Thuy-Quynh, die als erste 2009 von Moritz erfuhr und damit den Anfang markierte.\nSie traf genau zur richtigen Zeit am richtigen Ort ein und wurde zu unserem geheimen und vertrauten Begleiterin. Ihre Gegenwart war ein Geschenk und hat unsere Geschichte auf wundersame Weise bereichert.\n\nAuch wenn wir bedauern, dass wir euch alle nicht physisch hier haben können, ist eure Liebe und Unterstützung von unschätzbarem Wert. Wir freuen uns darauf, mit euch allen Geschichten zu teilen, gemeinsam zu lachen und die Freude unseres Zusammenseins zu erleben. Danke, dass ihr ein Teil unseres Lebens seid.",
      "intro.welcome.out": "Mit Liebe"
    },
    "fr": {
      "intro.welcome.title": "Chère famille, chers amis et proches",
      "intro.welcome.text": "Nous sommes heureux de vous annoncer que Thuy-Duc et Moritz sont partis en amoureux. Nous avons choisi de nous éloigner des traditions et avons célébré ce moment intime en compagnie de nos enfants uniquement.\n\nAyant étudié ensemble, obtenu leurs diplômes et travaillé côte à côte à plusieurs reprises, leur histoire s'est ainsi tissée au fil du temps. Pendant ce temps, nous avons formé notre propre famille avec les deux enfants les plus formidables. Le fait de grandir ensemble nous a liés bien plus que n'importe quel serment ne pourrait le faire.\n\nMême si nous ne formions pas un couple de même sexe, nous croyons en l'égalité des droits pour tous. L'adoption du mariage pour tous en septembre 2021 a été une avancée décisive pour l'égalité, renforçant notre décision de nous marier. Parallèlement, l'expérience de la pandémie nous a également poussés à franchir le pas et à sceller notre union.\n\nNous voulons remercier nos amis Benjamin et Michael, nos témoins de mariage. Leur amitié et soutien sont très importants pour nous, et nous sommes reconnaissants de les avoir avec nous.\n\nNous nous rappelons de Thuy-Quynh, la première à apprendre la nouvelle de Moritz en 2009, marquant ainsi le début de notre histoire. Elle était notre compagne secrète et de confiance.\n\nBien que nous regrettons de ne pas pouvoir vous avoir tous physiquement parmi nous, votre amour et votre soutien sont d'une valeur inestimable pour nous. Nous sommes impatients de partager des histoires avec vous, de rire ensemble et de vivre la joie de notre rassemblement. Merci d'être une part de nos vies.",
      "intro.welcome.out": "Avec amour"
    },
    "vn": {
      "intro.welcome.title": "Kính mến gia đình và các bạn thân yêu",
      "intro.welcome.text": "Chúng mình vui mừng chia sẻ tin vui: Thuy-Duc và Moritz đã kết hôn!\nTrong một quá trình riêng tư, thoát ly khỏi truyền thống và văn hóa xã hội, một thế giới chỉ thuộc về bốn chúng mình.\n\nSự việc học cùng nhau đến tốt nghiệp và vô số lần làm việc cùng nhau, chúng mình đã tạo nên câu chuyện của riêng mình. Trong thời gian đó, mình đã được lập gia đình với hai đứa trẻ tuyệt vời nhất. Sự việc này đã đem đến thêm hạnh phúc và niềm vui cho chúng mình. Không mong gì hơn. Sự lớn lên cùng nhau đã kết nối chúng mình nhiều hơn bất kỳ lời thề hôn nhân nào có thể tạo ra.\n\nBan đầu, chúng mình không nghĩ đến việc kết hôn.\nDù chúng mình không phải là đồng tính, nhưng chúng mình cho rằng mọi người đều nên có quyền và cơ hội bằng nhau. Việc Quốc hội thông qua Luật \"Hôn nhân cho mọi người\" vào tháng 9 năm 2021 đã là một bước quan trọng trong việc thúc đẩy sự công bằng. Sự việc này đã đóng góp vào ý định của chúng mình để kết hôn. Sau cùng, trong những thách thức của đại dịch, chúng mình đã quyết tâm để kết hôn.\n\nGửi ba mẹ yêu thương của chúng con, chúng con muốn bày tỏ lòng biết ơn sâu sắc về tình yêu, dạy dỗ, nuôi lớn và sự trao ra của ba mẹ.\n\nMặc dù chúng mình tiếc nuối vì không có gia đình và tất cả các bạn thân yêu ở đây mặt trận, tình yêu và sự hỗ trợ của gia đình và các bạn có ý nghĩa rất lớn với chúng mình.\nChúng mình rất mong được tụ tập với tất cả để chia sẻ những câu chuyện, tiếng cười và niềm vui của sự kết hôn của chúng mình.\nCảm ơn gia đình và các bạn thân yêu đã là một phần quan trọng trong cuộc sống của chúng mình.",
      "intro.welcome.out": "Với tình yêu và lòng biết ơn"
    }  
  };
  